kind: Service
apiVersion: v1
metadata:
  name: selling-guides-apache
  labels:
    stack: selling-guides
spec:
  selector:
    stack: selling-guides
    app: apache
  ports:
  - name: http
    port: 80
  - name: https
    port: 443
