apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: blog-apache
  labels:
    stack: blog
    app: apache
spec:
  selector:
    matchLabels:
      stack: blog
      app: apache
  template:
    metadata:
      name: blog-apache
      labels:
        app: apache
        stack: blog
    spec:
      imagePullSecrets:
      - name: stq
      containers:
      - name: apache
        image: storiqateam/wordpress:blog
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        volumeMounts:
        - name: wpdata
          mountPath: /var/www/html/blog
        - name: phpconf
          mountPath: /usr/local/etc/php/php.ini
          subPath: php.ini
        readinessProbe:
          httpGet:
            path: /blog
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 3
        livenessProbe:
          httpGet:
            path: /blog
            port: 80
          initialDelaySeconds: 60
          periodSeconds: 30
      volumes:
      - name: wpdata
        persistentVolumeClaim:
          claimName: blog
      - name: phpconf
        configMap:
          name: selling-guides-php

